SELECT 
COUNT (DISTINCT
  CONTRATO),
  --FACTURA_ID,COUNT(*),
  CASE
    WHEN (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)> 60 AND DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)<= 75) THEN "60-75"
    WHEN (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)> 75 AND DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)<= 90) THEN "75-90"
    END AS RANGO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  RANGO_CONTRATO ="3-30A60"
  AND TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-08-01"
  AND EXTRACT (MONTH
  FROM
    FECHA_ASIGNACION) =10
    GROUP BY 2
