WITH USUARIOSASIGNADOS AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
    AND FECHA_FACTURA ="2021-09-01"
    AND EXTRACT( MONTH FROM FECHA_ASIGNACION)=9
    AND RANGO_CONTRATO ="1-SIN VENCER"
),
USUARIOSPAGO20D AS (
SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
    AND FECHA_FACTURA ="2021-09-01"
    AND (EXTRACT( MONTH FROM FECHA_ASIGNACION)=9 AND RANGO_CONTRATO ="1-SIN VENCER" AND DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)> 20 OR FECHA_PAGO IS NULL)
),
USUARIOSPAGO21A26 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =9 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=26 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="1-SIN VENCER"
),
USUARIOSPAGO27A30 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =9 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=30 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="1-SIN VENCER"
    ),
USUARIOSPAGO30A45 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =10 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=30 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="2-0A30"
    ),
    USUARIOSPAGO45A55 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =10 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=45 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="2-0A30"
    ),
    USUARIOSPAGO55A60 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =10 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=55 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="2-0A30"
    ),
     USUARIOSPAGO60A75 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =11 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=60 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="3-30A60"
    ),
    USUARIOSPAGO75A90 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =11 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=75 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="3-30A60"
    ),
    USUARIOSPAGOMAS90 AS(
  SELECT
  DISTINCT CONTRATO
FROM
  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
  TIPO_SERVICIO IN ('INTERNET',
    'CABLE TICA',
    'TELEFONIA',
    'FTTH (JASEC)',
    'HOGARES CONECTADOS')
  AND FECHA_FACTURA ="2021-09-01"
  AND (EXTRACT (MONTH FROM FECHA_ASIGNACION) =12 )
    AND (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)>=90 OR FECHA_PAGO IS NULL)
    AND RANGO_CONTRATO ="4-60A90"
    ),
JOINTABLAS AS (
  SELECT
  a.CONTRATO AS A,
  b.CONTRATO AS B,
  c.CONTRATO AS C,
  d.CONTRATO AS D,
  e.CONTRATO AS E,
  f.CONTRATO AS F,
  g.CONTRATO AS G,
  h.CONTRATO AS H,
  i.CONTRATO AS I,
  j.CONTRATO AS J,
  FROM USUARIOSASIGNADOS a
  LEFT JOIN
  USUARIOSPAGO20D b
  ON a.CONTRATO=b.CONTRATO
  LEFT JOIN
  USUARIOSPAGO21A26 c
  ON b.CONTRATO=c.CONTRATO
  LEFT JOIN 
  USUARIOSPAGO27A30 d
  ON c.CONTRATO=d.CONTRATO
  LEFT JOIN 
  USUARIOSPAGO30A45 e 
  ON d.CONTRATO=e.CONTRATO
  LEFT JOIN
  USUARIOSPAGO45A55 f
  ON
  e.CONTRATO=f.CONTRATO
  LEFT JOIN
  USUARIOSPAGO55A60 g
  ON
  f.CONTRATO = g.CONTRATO
  LEFT JOIN 
  USUARIOSPAGO60A75 h 
  ON
  g.CONTRATO= h.CONTRATO
  LEFT JOIN 
  USUARIOSPAGO75A90 i 
  ON h.CONTRATO= i.CONTRATO
  LEFT JOIN
  USUARIOSPAGOMAS90 j
  ON i.CONTRATO=j.CONTRATO
)
SELECT COUNT(A) AS ASIGNADOS_MES, COUNT(B) ENTRADA_MOROSOS_20, COUNT(C) AS DE_21_A_26, COUNT (D) AS DE_26_A_30, COUNT (E) AS DE_30_A_45, COUNT(F) AS DE_45_A_55, COUNT(G) AS DE_55_A_60, COUNT(H) AS DE_60_A_75, COUNT (I) AS DE_75_A_90, COUNT(J) AS DE_90_A_120
FROM JOINTABLAS
